package shared.protocol;

public enum Comando {
    ATTACCA,
    RISPOSTA_ATTACCO,
    TURNO,
    FINE_PARTITA, 
    INVIA_NOME, 
    DISCONNETTI, 
    RISPOSTA, RISULTATO_ATTACCO, STATO, ASSEGNA_ID, ERRORE, AGGIORNA_Lobby, START
}
