package shared.protocol;

public enum Comando {
    ATTACCA,
    RISPOSTA_ATTACCO,
    TURNO,
    FINE_PARTITA, 
    INVIA_NOME, 
    DISCONNETTI, 
    RISPOSTA,
    RISULTATO_ATTACCO, 
    VITTORIA,
    SCONFITTA,
    ATTACCO_RICEVUTO,
    STATO, 
    ASSEGNA_ID, 
    ERRORE, 
    AGGIORNA_Lobby, 
    START,
    DISCONNESSIONE,
    POSIZIONA_NAVI,
    INIZIO_BATTAGLIA
}